modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="delightfulblocks"
version="1.0.0"
displayName="Delightful Blocks "
credits="Created By GigaStudios"
displayURL="https://gigastudiosllc.itch.io"
authors="Frosty, GigaStudios"
description="Created By GigaStudios"

[[dependencies.delightfulblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




